### ISSUE TITLE
Please publish recipe for iso.

### ISSUE THREAD

**Issue by tphyahoo** [LedgerHQ/ledger-starter-iso#1]
Hm... empty repo...

Please publish recipe for 

https://www.youtube.com/watch?v=HWIPfEilBHM

for review from the community.  Thank you!

**Comment by Morveus** [comment]
Hi,

Sorry about the empty repo, we've been very busy these days.
I'll post the recipe asap!

**Comment by Morveus** [comment]
Here is the recipe: https://github.com/LedgerHQ/ledger-starter-iso/blob/master/README.md
