### ISSUE TITLE
reproducible build 

### ISSUE THREAD

**Issue by tphyahoo** [LedgerHQ/ledger-starter-iso#2]
A signed, reproducible build would be great.

I'm not sure the best way to do this.

Maybe vagrant / packer:

https://www.vagrantup.com/docs/boxes/base.html

https://www.packer.io/intro/

**Comment by Morveus** [comment]
Hi,

Unfortunately we don't have enough requests to justify putting resources to this task. The recipe given here is enough to allow you to generate your own install.
